# Generated by Django 5.1.5 on 2025-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
